name: Build Pure-FTPd EL10 RPM

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      – uses: actions/checkout@v4

      – name: Build and Package
        run: |
          docker build \
            -f docker/Dockerfile.rpmbuild-pureftpd-el10 \
            -t pure-ftpd-el10:latest .
          docker run --rm -v ${{ github.workspace }}/output:/output pure-ftpd-el10:latest \
            bash -c "cd /home/builder/rpmbuild && rpmbuild -ba SPECS/pure-ftpd.spec && cp RPMS/*/* /output/"

      – uses: actions/upload-artifact@v4
        with:
          name: pure-ftpd-el10-rpms
          path: output/*.rpm
