name: Build Pure-FTPd EL10 RPM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -f docker/Dockerfile.rpmbuild-pureftpd-el10 \
            -t pure-ftpd-el10-build:latest .

      - name: Create build directory
        run: mkdir -p output

      - name: Run rpmbuild container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/output:/output \
            pure-ftpd-el10-build:latest \
            bash -c "
              set -euo pipefail; 
              cd /home/builder/rpmbuild; 
              rpmbuild -ba SPECS/pure-ftpd.spec; 
              cp RPMS/*/* /output/;
            "

      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pure-ftpd-el10-rpms
          path: output/*.rpm