name: Build Pure-FTPd EL10 RPM

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -f dockerfiles/Dockerfile.rpmbuild-pureftpd-el10 \
            -t pure-ftpd-el10-build:latest .

      - name: Create build directory
        run: mkdir -p output

      - name: Run rpmbuild container
        run: |
          docker run --rm \
            -u root \
            -v ${{ github.workspace }}/output:/output \
            pure-ftpd-el10-build:latest \
            bash -c "
              set -euo pipefail;
              rpmbuild --define '_topdir /home/builder/rpmbuild' -ba /home/builder/rpmbuild/SPECS/pure-ftpd.spec;
              cp /home/builder/rpmbuild/RPMS/*/* /output/;
              cp /home/builder/rpmbuild/SRPMS/* /output/;
              ls -lAh /output/;
            "
      - name: Upload RPM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pure-ftpd-el10-rpms
          path: |
            output/*.rpm
            output/*.src.rpm