name: Build Pure-FTPd EL10 RPM

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -f dockerfiles/Dockerfile.rpmbuild-pureftpd-el10 \
            -t pure-ftpd-el10-build:latest .

      - name: Create build directory
        run: mkdir -p output

      - name: Run rpmbuild container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/output:/output \
            pure-ftpd-el10-build:latest \
            bash -c "
              set -euo pipefail;
              # Build as 'builder' user
              su - builder -c 'cd /home/builder/rpmbuild && rpmbuild -ba SPECS/pure-ftpd.spec';
              # Copy artifacts back as root
              cp /home/builder/rpmbuild/RPMS/*/* /output/;
            "
      - name: Upload RPM artifacts
          name: pure-ftpd-el10-rpms
          path: output/*.rpm